name: PR Preview
on:
  pull_request:
    types: [opened,reopened,synchronize]
jobs:
  Publish-Surge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Get Pull-Request ID
      id: get-pr-id
      uses: kkak10/pr-number-action@v1.3
#----------
    - run: npm i
    - run: npm i hexo-cli -g
    - run: hexo g
#----------
    - name: If Fail
      if: failure()
      run: |
        hexo clean
        mkdir public
        echo "<!DOCTYPE html><html><head><title>Oops</title></head><body>page build faile</body></html>" >> public/index.html
    - name: Add Commit ID
      run: echo "${{ github.sha }}" >> public/commit-id.txt
    - name: Publish To Surge
      uses: yg/deploy-surge@v1.0.1
      with:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        DOMAIN_NAME: https://pr-preview-actions-${{ steps.get-pr-id.outputs.pr }}.surge.sh
        BUILD_DIRECTORY: public
