name: Send PR Preview Message
on:
  pull_request:
    types: [opened,reopened]
jobs:
  Send-Msg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Get Pull-Request ID
      id: get-pr-id
      uses: kkak10/pr-number-action@v1.3
    
    - name: Send Message
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: You Render PR Server's URL is <https://pr-preview-actions-${{ steps.get-pr-id.outputs.pr }}.surge.sh> <br /> You can see the commit-id of the site at <https://pr-preview-actions-${{ steps.get-pr-id.outputs.pr }}.surge.sh/commit-id.txt>
