name: Teardown PR Preview
on:
  pull_request:
    types: [closed]
jobs:
  Teardown-Surge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Get Pull-Request ID
      id: get-pr-id
      uses: kkak10/pr-number-action@v1.3
    - name: Teardown PR Preview
      run: surge teardown https://pr-preview-actions-${{ steps.get-pr-id.outputs.pr }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
    - name: Send Message
      if: success()
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: PR Preview Server has been deleted successfully
