name: Teardown PR Preview
on:
  pull_request:
    types: [closed]
jobs:
  Teardown-Surge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Get Pull-Request ID
      id: get-pr-id
      uses: kkak10/pr-number-action@v1.3
    - name: Teardown PR Preview
      uses: nelonoel/surge-sh-teardown@v1.0.4
      with:
        template: "https://pr-preview-actions-${{ steps.get-pr-id.outputs.pr }}.surge.sh"
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}
